// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeaJ2iqkeIGbx6a8hkBA1h-PLrz-V5gZo',
    appId: '1:414718306936:web:d9cb913c032a5e2f2d1b8d',
    messagingSenderId: '414718306936',
    projectId: 'moivexpapp',
    authDomain: 'moivexpapp.firebaseapp.com',
    storageBucket: 'moivexpapp.firebasestorage.app',
    measurementId: 'G-CJX1ZR91S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_LwbL_1ng4e9YoZpXFYbyoWxEF_kkDY0',
    appId: '1:414718306936:android:74828008a0165c0f2d1b8d',
    messagingSenderId: '414718306936',
    projectId: 'moivexpapp',
    storageBucket: 'moivexpapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTrCnG-6GTbIfhY6beLo9x9nL3Qj-GZpQ',
    appId: '1:414718306936:ios:bd01a8fbcdceb3572d1b8d',
    messagingSenderId: '414718306936',
    projectId: 'moivexpapp',
    storageBucket: 'moivexpapp.firebasestorage.app',
    iosBundleId: 'com.example.appflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeaJ2iqkeIGbx6a8hkBA1h-PLrz-V5gZo',
    appId: '1:414718306936:web:e4a07c9780d1ce482d1b8d',
    messagingSenderId: '414718306936',
    projectId: 'moivexpapp',
    authDomain: 'moivexpapp.firebaseapp.com',
    storageBucket: 'moivexpapp.firebasestorage.app',
    measurementId: 'G-6YFNC9WXME',
  );
}
